import type { Metadata } from "next";
import AppThemeProvider from "./AppThemeProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Provides the root HTML document structure for the app router.
 *
 * @param props - The nested route content to render inside the document body.
 * @returns The shared application shell for every route.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppThemeProvider>{children}</AppThemeProvider>
      </body>
    </html>
  );
}
