'use client';

import AppThemeProvider from './AppThemeProvider';
import './globals.css';
import AppNavbar from '@/components/navigation/AppNavbar/AppNavbar';
import {
  LearningTasksContext,
  learningTasksReducer,
  LearningTasksState,
} from '@/context/learningTasks/learningTasks.store';
import { useReducer } from 'react';
import exampleLearningTasks from '@/temp/learningTasks';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

/**
 * Provides the root HTML document structure for the app router.
 *
 * @param props - The nested route content to render inside the document body.
 * @returns The shared application shell for every route.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState: LearningTasksState = { learningTasks: exampleLearningTasks };
  const [state, dispatch] = useReducer(learningTasksReducer, initialState);

  return (
    <html lang="en">
      <body>
        <AppThemeProvider>
          <AppNavbar />
          <LearningTasksContext.Provider value={{ state, dispatch }}>
            {children}
          </LearningTasksContext.Provider>
        </AppThemeProvider>
      </body>
    </html>
  );
}
